# Generated by Django 4.1.2 on 2022-10-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('total_followers', models.PositiveIntegerField(default=0)),
                ('total_following', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('stargazers_count', models.PositiveIntegerField(default=0)),
                ('watchers_count', models.PositiveIntegerField(default=0)),
                ('forks_count', models.PositiveIntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='stats.developer')),
            ],
            options={
                'unique_together': {('developer', 'name')},
            },
        ),
    ]
